Home work1
Shtuka1993/phplab-tasks pull request #1
Opened 2020-07-08 16:41 UTC by Shtuka1993

Home work one

2020-07-09 07:59 UTC, yderevianko-cartera requested changes

2020-07-09 07:59 UTC, yderevianko-cartera commented on src/01-basics.php
> +    define("Q1","first");
По перше константи не рекомендовано дефайнити всереди функції так як це спричиняє помилки типу:

GetMinuteQuarterTest::testPositive with data set #1 (5, 'first')
Constant Q1 already defined
/vagrant/www/phplab-tasks/src/01-basics.php:15
/vagrant/www/phplab-tasks/tests/GetMinuteQuarterTest.php:12

І взагалі є суть створбвати константи якщо вони будуть використовуватися принаймі в 2-ох різних місцях, а в цій домашці вони можуть просто бути замінени на стрічки в середині switch.

2020-07-09 07:59 UTC, yderevianko-cartera commented on src/01-basics.php
> +        $quarter = (int)(($minute-1)/15)+1;
PSR-1\PSR-2 
 $quarter = (int)(($minute - 1) / 15) + 1;

2020-07-09 07:59 UTC, yderevianko-cartera commented on src/01-basics.php
> +        for( $i=0; $i<3; $i++ ) {
PSR
for ($i = 0; $i < 3; $i++) {

2020-07-09 07:59 UTC, yderevianko-cartera commented on src/01-basics.php
> +    if (strlen($input) === 6) {
Tут все працює, але можна ще додати конвертацію типу щоб php сам не вгадував.
Також можна зберегти собі розмір стрічки і зробити логіку трохи більш динамічною.

$n = strlen($input);
...
for ($i = 0; $i < $n / 2; $i++) {
    $s1 += (int)$input[$i];
    $s2 += (int)$input[$n - 1 - $i];

2020-07-09 21:57 UTC, Shtuka1993 commented on src/01-basics.php
> +    define("Q1","first");
Дякую за рекомендації. Прибрав константи. В принципі в моєму коді "fourth" використано двічі, то ж думав що можна використати константи.

2020-07-09 21:57 UTC, Shtuka1993 commented on src/01-basics.php
> +        $quarter = (int)(($minute-1)/15)+1;
Дякую. Працюю над цим. Виправив.

2020-07-09 21:58 UTC, Shtuka1993 commented on src/01-basics.php
> +        for( $i=0; $i<3; $i++ ) {
Дякую. Працюю над цим. Виправив.

2020-07-09 21:59 UTC, Shtuka1993 commented on src/01-basics.php
> +    if (strlen($input) === 6) {
Оновив.

2020-07-14 08:34 UTC, yderevianko-cartera requested changes

2020-07-14 08:34 UTC, yderevianko-cartera commented on src/01-basics.php
> +
Краще не використовувати return в свічі. Краще присвоювати результат якійсь змінній і в кінці зробити один return.
І не потрібно пустий рядок перед return якщо він перший рядок в блоці.

2020-07-15 12:21 UTC, Shtuka1993 commented on src/01-basics.php
> +
Оновив.

2020-07-15 12:26 UTC, yderevianko-cartera requested changes

2020-07-15 12:26 UTC, yderevianko-cartera commented on src/01-basics.php
> +            $result = "fourth";
тут мабуть потрібно одразу return 'fourth'

2020-07-15 12:44 UTC, yderevianko-cartera approved these changes

2020-07-15 12:45 UTC, Shtuka1993 commented on src/01-basics.php
> +            $result = "fourth";
Дякую. Виправив.

2020-07-15 12:59 UTC, merged