Home work2
Shtuka1993/phplab-tasks pull request #2
Opened 2020-07-08 18:19 UTC by Shtuka1993

Home Work Two

2020-07-09 08:29 UTC, yderevianko-cartera requested changes

2020-07-09 08:29 UTC, yderevianko-cartera commented on src/02-strings.php
> +    for ($i=0; $i<$length; $i++) {
PSR spaces

2020-07-09 08:29 UTC, yderevianko-cartera commented on src/02-strings.php
> +        }
Робичий спосіб, але ще можеш глянути до вбудованих php функцій для роботи з масивами і стрічками і два найпопулярніші з них: explode, implode.

Приклад можливого варіанта з використанням вбудованих функцій (це не обовязково так робити):


```
function snakeCaseToCamelCase(string $input)
{
    $inputArray = explode('_', $input);
    $inputArray = array_map(
        function ($elem) {
            return ucfirst($elem);
        },
        $inputArray
    );

    return lcfirst(implode('', $inputArray));
}

```

2020-07-09 08:29 UTC, yderevianko-cartera commented on src/02-strings.php
> +    $length = mb_strlen($word) - 1;
Хороший варіант )) 
Тільки власні (не вбудовані функції) потрібно називати camelCase і перед кожним return потрібно ставити пустий рядок.

2020-07-09 08:29 UTC, yderevianko-cartera commented on src/02-strings.php
> +    $result = '';
Не потрібна змінна так як вона завжди буде ініціалізована в if\else

Також потрібно ставити пробіл до і після '.'

2020-07-09 22:04 UTC, Shtuka1993 commented on src/02-strings.php
> +        }
Дякую. Оновлю код.

2020-07-10 08:12 UTC, Shtuka1993 commented on src/02-strings.php
> +    for ($i=0; $i<$length; $i++) {
Оновив.

2020-07-10 08:12 UTC, Shtuka1993 commented on src/02-strings.php
> +    $length = mb_strlen($word) - 1;
Оновив.

2020-07-10 08:13 UTC, Shtuka1993 commented on src/02-strings.php
> +    $result = '';
Оновив.

2020-07-10 08:15 UTC, Shtuka1993 commented on src/02-strings.php
> +        }
Дякую. Спробую реалізувати.

2020-07-15 12:57 UTC, yderevianko-cartera approved these changes

2020-07-15 13:24 UTC, Shtuka1993 commented on src/02-strings.php
> +        }
Я додав цей варіант собі в код, та все ж зберіг старий код.

2020-07-15 13:24 UTC, merged